[phases.setup]
nixPkgs = [
    "python310",
    "postgresql_16",
    "libmysqlclient",
    "gcc",
    "unixODBC"
]

[phases.install]
cmds = [
    "python3 -m venv /opt/venv",  # Crea el entorno virtual
    "/opt/venv/bin/python -m ensurepip --default-pip",  # Instala pip
    "/opt/venv/bin/python -m pip install --upgrade pip setuptools wheel",  # Asegura que pip est√© actualizado
    "/opt/venv/bin/pip install -r requirements.txt"  # Instala dependencias
]

[start]
cmd = "/opt/venv/bin/gunicorn --workers=4 FerreFac.wsgi:application --bind 0.0.0.0:8000"
